
export enum EApplicationStep {
    PRESCORING = 'PRESCORING',
    OFFERS = 'OFFERS',
    SCORING = 'SCORING',
};

export enum EApplicationStatus {
    PREAPPROVAL = 'PREAPPROVAL',
    CLIENT_DENIED = 'CLIENT_DENIED',
    APPROVED = 'APPROVED',
    CC_DENIED = 'CC_DENIED',
    CC_APPROVED = 'CC_APPROVED',
    PREPARE_DOCUMENTS = 'PREPARE_DOCUMENTS',
    DOCUMENT_CREATED = 'DOCUMENT_CREATED',
    DOCUMENTS_SIGNED = 'DOCUMENTS_SIGNED',
    CREDIT_ISSUED = 'CREDIT_ISSUED'
};

export const NumAppStatus: Record<EApplicationStatus, number> = {
    CLIENT_DENIED: 0,
    CC_DENIED: 0,
    PREAPPROVAL: 1,
    APPROVED: 2,
    CC_APPROVED: 3,
    PREPARE_DOCUMENTS: 4,
    DOCUMENT_CREATED: 5, 
    DOCUMENTS_SIGNED: 6,
    CREDIT_ISSUED: 7,
};

