
export enum EApplicationStep {
    PRESCORING = 'PRESCORING',
    OFFERS = 'OFFERS',
    SCORING = 'SCORING',
};

export enum EApplicationStatus {
    PREAPPROVAL = 'PREAPPROVAL',
    CLIENT_DENIED = 'CLIENT_DENIED',
    APPROVED = 'APPROVED',
    CC_DENIED = 'CC_DENIED',
    CC_APPROVED = 'CC_APPROVED',
    PREPARE_DOCUMENTS = 'PREPARE_DOCUMENTS',
    DOCUMENTS_CREATED = 'DOCUMENTS_CREATED',
    DOCUMENTS_SIGNED = 'DOCUMENTS_SIGNED',
    CREDIT_ISSUED = 'CREDIT_ISSUED'
}